version: 2.1

orbs:
  hugo: circleci/hugo@1.3.1

jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout

      - run:
          name: Update theme
          command: git submodule update --init --recursive

      - run:
          name: Build Hugo site
          command: hugo --destination=workspace/public

      # Persist the 'build' directory to the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - public

  push build:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Push build folder to GitHub
          command: |
            # Configure Git identity
            git config --global user.name "olawanlejoel"
            git config --global user.email "olawanlejoel@users.noreply.github.com"

            # Clone the repository (replace <your-repo> with your actual repository URL)
            git clone --branch deploy --depth 1 https://olawanlejoel:${GITHUB_TOKEN}@github.com/olawanlejoel/hugo-try-circleci.git deployment

            # Copy the 'public' directory to the deployment folder
            cp -R workspace/public deployment

            # Navigate to the deployment folder
            cd deployment

            # Commit and push changes
            git add .
            git commit -m "Auto generated"
            git push

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - push build:
          requires:
            - build