version: 2.1

executors:
  hugo-executor:
    docker:
      - image: cibuilds/hugo:latest

jobs:
  build:
    executor: hugo-executor
    steps:
      - checkout

      - run:
          name: Update theme
          command: git submodule update --init --recursive

      - run:
          name: Build Hugo site
          command: hugo --destination=workspace/build

      # Persist the 'build' directory to the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  deploy:
    executor: hugo-executor
    steps:
      - attach_workspace:
          at: /workspace

      - run:
          name: Configure Git
          command: |
            git config --global user.name "olawanlejoel"
            git config --global user.email "olawanlejoel@users.noreply.github.com"
            git clone ${CIRCLE_REPOSITORY_URL} /repo
            cd /repo
            git checkout -b deploy
            rsync -av --delete /workspace/public/ /repo/
            git add .
            git commit -m "Auto generated from ${CIRCLE_SHA1}"
            git push origin deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
