version: 2.1

executors:
  hugo-executor:
    docker:
      - image: cibuilds/hugo:latest

jobs:
  build:
    executor: hugo-executor
    steps:
      - checkout

      - run:
          name: Update theme
          command: git submodule update --init --recursive

      - run:
          name: Build Hugo site
          command: hugo --destination=workspace/build

      # Persist the 'build' directory to the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  deploy:
    executor: hugo-executor
    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Log the content of the 'build' directory
          command: |
            # List the contents of the 'build' directory
            ls -l workspace/build

            # Print the content of a specific file, e.g., index.html
            cat workspace/build/index.html
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
