name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main # Adjust this to the main branch name of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Set Up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo

      - name: Upload artifact
        # Automatically uploads an artifact from the '_site' directory
        uses: actions/upload-artifact@v3
        with:
          name: compiled-site
          path: public
  # Deploy job
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # Set permissions to write to the repo
      contents: write
    steps:
      # Checkout the repo and download the artifacts
      - uses: actions/checkout@v4
        with:
          # Branch to commit and push the artifacts
          ref: deploy
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-site
          path: public
      # Commit and push to the repo's <deploy> branch
      - name: Commit and push
        # Replace "VirtuaCreative" and "virtuacreative" with your GH org or user name
        run: |
          git config user.name "olawanlejoel"
          git config user.email "olawanlejoel@users.noreply.github.com"
          git pull origin deploy
          git add public
          git commit -m "Auto generated from ${GITHUB_SHA::7}"
          git push
